ministryofjustice/opg-data-lpa

.gitignore
docs/pull_request_template.md
integration_tests/integration_tests.md
integration_tests/v1/conftest.py
integration_tests/v1/requirements.txt
integration_tests/v1/response_schemas/lpa_online_tool_schema.json
integration_tests/v1/response_schemas/use_an_lpa_schema.json
integration_tests/v1/test_lpa_online_tool.py
integration_tests/v1/test_use_an_lpa.py

So we have something we can use to compare our version with
Super basic for now, happy path and 404 (id not found)

IN-255 integration tests for existing API

---

.circleci/config.yml
.envrc
.secrets.baseline
docs/ci_scripts/cancel_builds.py
docs/ci_scripts/login_code_artifact.sh
docs/ci_scripts/requirements.txt

- Implement cancel redundant builds
- Implement small build containers

IN-285 save circle credits

---

integration_tests/v1/response_schemas/healthcheck_schema.json
integration_tests/v1/test_healthcheck.py
lambda_functions/v1/functions/lpa/app/api/handlers.py
lambda_functions/v1/functions/lpa/app/api/helpers.py
lambda_functions/v1/functions/lpa/app/api/resources.py
lambda_functions/v1/functions/lpa/app/api/sirius_helpers.py
lambda_functions/v1/functions/lpa/app/sirius_service/sirius_handler.py
lambda_functions/v1/openapi/lpa-openapi.yml
lambda_functions/v1/tests/routes/conftest.py
lambda_functions/v1/tests/routes/test_healthcheck.py
lambda_functions/v1/tests/routes/test_lpa_online_tool.py
lambda_functions/v1/tests/routes/test_use_an_lpa.py
lambda_functions/v1/tests/sirius_service/test_cache_available.py
lambda_functions/v1/tests/sirius_service/test_get_sirius_data_from_cache.py
lambda_functions/v1/tests/sirius_service/test_put_sirius_data_in_cache.py
lambda_functions/v1/tests/sirius_service/test_send_request_to_sirius.py
lambda_functions/v1/tests/sirius_service/test_sirius_available.py

Added a sirius and redis check to the healthcheck endpoint, plus some tests
* [ x] I have run the integration tests (results below)

IN-324 expand the healtcheck endpoint

---

lambda_functions/v1/openapi/lpa-openapi.yml
terraform/environment/dns.tf

No idea why these were removed. They shouldn't be..

IN-WTH add permissions back in

---

.circleci/config.yml
.secrets.baseline

add dockerhub credentials to pipeline

IN-455 add dockerhub credentials to pipeline

---

lambda_functions/v1/functions/lpa/app/api/handlers.py
lambda_functions/v1/functions/lpa/app/api/resources.py
lambda_functions/v1/openapi/lpa-openapi.yml
lambda_functions/v1/tests/routes/conftest.py
lambda_functions/v1/tests/routes/test_request_code.py

https://opgtransform.atlassian.net/browse/VEGA-473

VEGA-473 Add request code handler

---

terraform/environment/terraform.tfvars.json

Use are using int env for their preprod account.
NA
NA

IN-561 add use preprod to dev lpa data allow list

---

.circleci/config.yml
.secrets.baseline

swap cicle steps around

---

docs/support_scripts/aws/getcreds.go

Change the creds to our read only user anyone can assume.

IN-562 change the assume user for get creds

---

lambda_functions/v1/requirements/dev-requirements.txt
lambda_functions/v1/requirements/requirements.txt

fix pyjwt version

---

README.md
integration_tests/v1/conftest.py
integration_tests/v1/response_schemas/use_an_lpa_schema.json
integration_tests/v1/test_request_code.py
lambda_functions/v1/functions/lpa/app/api/handlers.py
lambda_functions/v1/functions/lpa/app/api/resources.py
lambda_functions/v1/functions/lpa/app/flask_lambda.py
lambda_functions/v1/requirements/dev-requirements.txt
lambda_functions/v1/requirements/requirements.txt
lambda_functions/v1/tests/routes/test_request_code.py
mock_sirius_backend/api/lpas/handlers.py
mock_sirius_backend/app.py
mock_sirius_backend/sirius_public_api.yaml

Implement the letter request API into the mock service and fix the json interpretation of body content so it passes it along correctly.

Uml 1194 older lpa fixes

---

mock_sirius_backend/api/lpas/mock_data/use_an_lpa_response.json

https://opgtransform.atlassian.net/browse/UML-1200

UML1200: some changes to mock data to reflect correctly with seeded data 

---

.circleci/config.yml

IN-702 update tf to 14.11

---

.github/workflows/scanner.yml

Add action to scan for packages

add action to scan for packages

---

.circleci/config.yml
docs/ci_scripts/login_code_artifact.sh
integration_tests/v1/conftest.py
terraform/environment/provider.tf
terraform/environment/variables.tf

to replace the CI user so it is not using Sirius any more.
- Search and replace (with visual checks) 
- minor lint performed by git hooks
-
N/A

update CI User to integrations-ci

---

.circleci/config.yml
README.md

The branch has already been moved, this just updates CI to match

Rename default branch from master to main

---

.github/CODEOWNERS

Adds Starfox team members as code owners for infrastructure as we are taking on the management in a more formal capacity. Just allows us to understand any changes being made as we now own the support and code!
Via github code owners

SP-796 - Added codeowners for infrastructure

---

.github/workflows/deploy.yml

SP-771 - use correct TF directory

---

terraform/environment/alerts.tf
terraform/environment/terraform.tfvars.json
terraform/environment/variables.tf

SP-825 - Remove redundant/misconfigured 4XX Alert #patch

---

lambda_functions/v1/openapi/lpa-openapi.yml
mock_sirius_backend/sirius_public_api.yaml

Updates OpenAPI spec statuses to include "Return - unpaid".
* N/A
* N/A
* N/A
* N/A

Add "Return - unpaid" status to OpenAPI spec

---

.github/workflows/build.yml
.github/workflows/deploy.yml
terraform/environment/modules/lambda/lambda.tf
terraform/environment/stage.tf

SP-905 - Switch API Gateway TLS to 1.2 #minor

---

.github/workflows/build.yml
.github/workflows/destroy_workspaces.yml
lambda_functions/v1/requirements/requirements.txt
terraform/environment/modules/lambda/lambda.tf
terraform/environment/terraform.tfvars.json

SP-920 - Update opg-sirius-service to get the caching working #patch

---

.github/workflows/destroy_workspaces.yml

SP-921 - Disable terraform acitons wrapper #patch

---

lambda_functions/v1/functions/lpa/app/config.py
lambda_functions/v1/requirements/dev-requirements.txt
lambda_functions/v1/requirements/requirements.txt
terraform/environment/modules/lambda/lambda.tf

SP-947 adding GET request timeout #minor

---

.github/workflows/build.yml
README.md
integration_tests/v1/conftest.py
lambda_functions/v1/functions/lpa/app/__init__.py
lambda_functions/v1/openapi/lpa-openapi.yml
lambda_functions/v1/requirements/requirements.txt
lambda_functions/v1/tests/routes/conftest.py

The current specification for ual requests for lpa collections is incorrect and gives instead the make a lpa response
- fix response specification
- fix request parameter
- let ephemeral environments live for 4 hours
- fix integration test on use-an-lpa/lpas/requestCode
- address deprecation warnings about charset
* ~I have added relevant logging with appropriate levels to my code~
* ~I have added tests to prove my work~

Provide a corrected spec for path

---

terraform/environment/modules/stage/stage.tf
terraform/environment/modules/stage/variables.tf
terraform/environment/stage.tf

Associate the API Gateway Stages with the integrations AWS WAF ACL in a permissive/count mode as part of ticket [SP-1012](https://opgtransform.atlassian.net/browse/SP-1012)

SP-1015 - Associate API Gateway Stage with WAF ACL #minor

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Currently the integration environment is stale and not receiving updates.
Fixes SP-1061 #patch
Copied development workspace configuration and altered it to point at integration
* N/A
* N/A
* N/A
* N/A
* N/A

Deploy infra to integration environment

---

.pre-commit-config.yaml
.secrets.baseline
terraform/environment/.terraform.lock.hcl
terraform/environment/elasticache.tf
terraform/environment/lambda.tf
terraform/environment/stage.tf
terraform/environment/vpc.tf

Terraform creds were failing
Fixed a couple of bits and pieces with this:
- Updated terraform
- Updated pre commits
- Updated lock file to handle M1 and arm checksums
NA

check why creds are failing

---

.github/workflows/deploy.yml

update path to live

---

lambda_functions/v1/requirements/requirements.txt

_Upgrade re quested by dependabot, re-done by me so can build_

dependabot change , requested by me to have permissions

---

.github/workflows/build.yml

UML-3357 Extract branch name safely

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/destroy_workspaces.yml

Use the standard GHA secret names for AWS secrets to allow resuable workflow to be used.

UML-3384: Use standard GHA secret names

---

.github/workflows/analysis-codeql.yml
.github/workflows/analysis-tfsec-to-github-security.yml

Add CodeQL and TFSec code analysis tools

UML-3351: Add code analysis tool

---

.github/workflows/destroy_workspaces.yml

Fix destroy workspace job

---

.github/workflows/_docker_build_scan_push.yml
.github/workflows/workflow_path_to_live.yml
.github/workflows/workflow_pr.yml

Prefixed Lambda images with `main-`, preventing the image from being inadvertently removed from ECR. 
Fixes LPAL-1300
Learned how our ECR lifecycle policy works and is applied

LPAL-1300: prefix tags with main

---

.github/workflows/_docker_build_scan_push.yml

LPAL-1300: prefix image tags with main

---

lambda_functions/v1/requirements/requirements.txt

_For security, upgrade requests_
_update to requirements.txt_

bump requests

---

terraform/environment/alerts.tf

UML-3396: fix data block and sns topic

---

terraform/environment/modules/stage/stage.tf

SP-2339 - Correct JSON encoding in API Gateway logs #patch

---

.github/workflows/_docker_build_scan_push.yml

Adding trivy rate limit fix

---

lambda_functions/v1/Dockerfile-Function

Bump python ver to 3.13 from 3.12

Update python image

---

lambda_functions/v1/Dockerfile-Function
lambda_functions/v1/functions/lpa/app/config.py
terraform/environment/lambda.tf

Revert python update changes

---

.github/workflows/workflow_path_to_live.yml

SP-2471 - Deploy to Integration as part of the Path to Live #minor

---

terraform/environment/lambda.tf

SP-2527 - See if increasing memory stops container timeouts #minor

---

.github/workflows/workflow_path_to_live.yml

SP-2787 - Add Path to Live SSH Key access #minor

---

terraform/environment/scripts/workspace_cleanup.sh

So it doesn't get automatically deleted #patch

Add "demo" to protected workspaces

---

lambda_functions/v1/functions/lpa/app/config.py
terraform/environment/elasticache.tf
terraform/environment/lambda.tf

SP-2995 - Update Elasticache #minor

---

.pre-commit-config.yaml
.secrets.baseline

Updates detect-secrets to v1.5.0

UML-4060: update detect-secrets

---

lambda_functions/v1/requirements/dev-requirements.txt

It's been moved into the repo now
#patch

Remove opg-sirius-service dependency
